// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260930140147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("api.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "Christopher Nolan",
                            Genre = "Sci-Fi, Action",
                            Overview = "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            Status = "Completed",
                            Title = "Inception",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "Vince Gilligan",
                            Genre = "Crime, Drama",
                            Overview = "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
                            Rating = 9.5,
                            ReleaseYear = 2008,
                            Status = "Completed",
                            Title = "Breaking Bad",
                            Type = "TVShow"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "Frank Herbert",
                            Genre = "Science Fiction",
                            Overview = "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family.",
                            Rating = 9.0,
                            ReleaseYear = 1965,
                            Status = "In Progress",
                            Title = "Dune",
                            Type = "Book"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "Pink Floyd",
                            Genre = "Progressive Rock",
                            Overview = "The eighth studio album by English rock band Pink Floyd, exploring themes of conflict, greed, time, and mental illness.",
                            Rating = 9.3000000000000007,
                            ReleaseYear = 1973,
                            Status = "Completed",
                            Title = "The Dark Side of the Moon",
                            Type = "Album"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
